### ISSUE TITLE
Cell 3, 'unexpected' output

### ISSUE THREAD

**Issue by jorisvanzundert** [interedition/paceofchange#1]
Not a biggy, but there's output from building on the fly due the contents of the Docker image…

 /opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/opt/conda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

I guess if we really wanted to, we could make the image so that it already has these things built?

**Comment by mcburton** [comment]
This is being fixed upstream in the Jupyter project's docker-stacks so we need to just wait for them to merge the fix.
https://github.com/jupyter/docker-stacks/pull/289
