### ISSUE TITLE
Multiprocessing hanging again

### ISSUE THREAD

**Issue by mcburton** [interedition/paceofchange#5]
The multiprocessing code isn't working in the Docker container in the notebook-overhaul branch.

- Doesn't work in the Docker container in development mode with 4 or 7 gigs of ram with either two or four CPUS
- Does work outside of the container when running in a virtual environment.

We might consider exploring other options such as [pipenv](https://github.com/kennethreitz/pipenv) as a means of bundling everything together.

**Comment by mcburton** [comment]
comments from @jorisvanzundert 

So, I ran the master branch code. That worked.

Then I switched back to notebook-overhaul, tried 3 CPUs, 5Gb. But that didn't work. 
(An added CPU doesn't even make it faster, it seems. It'll eat the CPU, but does not speed up, weirdly enough.)

Then I tried 2 CPUs, 6Gb, then 7Gb. That *almost* got it to finish (stuck at 700), then it peters out.

Not all runs did use huge amounts of ram btw. The highest usage I was able to monitor was 5.01Gb, when I ran it with 6Gb for Docker. Weirdly enough, when I then ran it with 7Gb for Docker, the numbers were *lower*, like 4.82Gb. But I guess there's a lot of caching going on, maybe?

In any case, I can't give it yet more memory, as I have none to give on this machine. But it also seems to me that more memory shouldn't be the issue actually? If we did it right, it shouldn't consume more than the code in the master branch, no? Were some of the parameters changed, or was more/different data used?

Another thing I noticed is that the list the notebook prints out of the err.. not exactly the regression iterations, but something like modulus 50 iterations, behaves somewhat weird. It doesn't go up by 50 in a neatly fashion, but shows that one of the batches/pools(?) (notice that '400') is returning very tardy. It's a pool of 4 parallel computed regression calculations of course, so it doesn't need to mean anything. But I thought I'd better report it nonetheless.

0
50
100
150
200
250
300
350
450
500
400
600
650
700

**Comment by mcburton** [comment]
I must have done something in the notebook-overhaul branch to cause this race condition.

**Comment by mcburton** [comment]
I have identified the problematic code block. For some reason, generating the histogram is causing the multiprocessing to hang.

```py
### DEFACTORING INSPECTION
plt.style.use('ggplot')
pd.Series([x[1] for x in wordcounts.most_common(n=3200)]).hist(bins=720, figsize=(12,2))
```

**Comment by jorisvanzundert** [comment]
Hi Matt,

That's... so weird. I haven't read thoroughly through the notebook yet, so
I can't say anything much helpful.

I did look at the coupling between those two code bits though
(tentatively). And as far as I can see, there are non, no interfering ones
in any case.

The first thing that occurred to me was that the polling of the data to
produce the chart somehow changes the data structure in a way that would
mess up the pooling process. But 1) python is by reference and not by value
if I remember correctly (so it shouldn't be some Python quirk, and 2) you
didn't actively rewrite the data, as far as I see; nor accidentally.

In any case, what you could try, is to copy the wordcounts variable (
https://docs.python.org/3.5/library/copy.html) before you use it to ensure
absolutely no bindings between the counts that you use for the chart, and
the ones that are used for Ted's code. But I would be rather surprised (and
most interested) if the solves it.

I also wondered if pandas (that's one we specifically imported?) interferes
somehow with the data shape that Ted's draws from numpy. But this would
seem exotic to me.

So still weird. Another thing could be that the data somehow gets 'locked'
so some pool can't reach it, but how and why would be beyond me. Again this
would require some of the structures to become over written, but as it
seems Ted uses immutable tuplets mostly.

Sorry I can't be much more of a help at the moment. If my more thorough
reading turns up anything, I'll let you know of course.

Cheers
--J.

-- 

*Joris J. van Zundert*
*address  *Van Exelstraat 33, 3602 PE  Maarssen, The Netherlands
*email  *joris.van.zundert@gmail.com   *skype*  joris.van.zundert
*irc *reynaert   *twitter *@brandaen   *mobile  *+31624461051

-------


*Jack Sparrow: I thought you were supposed to keep to the code.Mr. Gibbs:
We figured they were more actual guidelines.*

**Comment by mcburton** [comment]
see code commit for details. But when I spent the weekend thinking about it i realized it was a memory issue. When I changed the bin size on the histogram it works.

**Comment by jorisvanzundert** [comment]
Wuh..? A simple histogram puts Python/Jupyter out of memory?? that's
ominous. But well, fixed is fixed. Excellent!

Cheers
--J.

-- 

*Joris J. van Zundert*
*address  *Van Exelstraat 33, 3602 PE  Maarssen, The Netherlands
*email  *joris.van.zundert@gmail.com   *skype*  joris.van.zundert
*irc *reynaert   *twitter *@brandaen   *mobile  *+31624461051

-------


*Jack Sparrow: I thought you were supposed to keep to the code.Mr. Gibbs:
We figured they were more actual guidelines.*
